# -*- coding: utf-8 -*-
import re
P="/sessions/jolly-practical-gauss/mnt/corazon/practica_corazon/public/cerebro.html"
h=open(P,encoding="utf-8").read()
POOL='''const POOL=[
 {id:1,cat:"lobulos",q:"El surco que separa el lóbulo frontal del parietal es el:",o:["Surco lateral","Surco central","Surco parietooccipital","Surco calcarino"],c:1,e:"El surco central (de Rolando) separa el lóbulo frontal del parietal y limita las cortezas motora y sensitiva."},
 {id:2,cat:"lobulos",q:"El giro PREcentral corresponde a la corteza:",o:["Sensitiva primaria","Motora primaria","Visual primaria","Auditiva primaria"],c:1,e:"El giro precentral (delante del surco central) es la corteza motora primaria; controla el hemicuerpo contralateral."},
 {id:3,cat:"lobulos",q:"El giro POSTcentral corresponde a la corteza:",o:["Motora primaria","Somatosensorial primaria","Visual primaria","Del lenguaje"],c:1,e:"El giro postcentral es la corteza sensitiva general (somatosensorial) primaria."},
 {id:4,cat:"lobulos",q:"En la profundidad del surco lateral (de Silvio) se encuentra:",o:["El cuerpo calloso","La ínsula","El tálamo","El cerebelo"],c:1,e:"La ínsula queda oculta en el fondo del surco lateral; solo se ve separando sus bordes."},
 {id:5,cat:"lobulos",q:"El surco parietooccipital separa los lóbulos:",o:["Frontal y parietal","Parietal y occipital","Temporal y occipital","Frontal y temporal"],c:1,e:"El surco parietooccipital separa el lóbulo parietal del occipital."},
 {id:6,cat:"lobulos",q:"El procesamiento visual primario ocurre en el lóbulo:",o:["Frontal","Temporal","Occipital","Parietal"],c:2,e:"El lóbulo occipital contiene la corteza visual primaria."},
 {id:7,cat:"lobulos",q:"Los dos hemisferios cerebrales están separados por el:",o:["Surco central","Surco longitudinal cerebral","Surco lateral","Surco calcarino"],c:1,e:"El surco longitudinal cerebral (interhemisférico) separa ambos hemisferios; aloja la hoz del cerebro y las arterias cerebrales anteriores."},
 {id:8,cat:"lobulos",q:"La mayor comisura que conecta ambos hemisferios es el:",o:["Fórnix","Cuerpo calloso","Comisura anterior","Septum pelúcido"],c:1,e:"El cuerpo calloso es la mayor comisura interhemisférica."},
 {id:9,cat:"lobulos",q:"El pliegue de duramadre en forma de hoz entre los hemisferios es la:",o:["Tienda del cerebelo","Hoz del cerebro","Diafragma selar","Hoz del cerebelo"],c:1,e:"La hoz del cerebro es el pliegue sagital de duramadre en el surco longitudinal."},
 {id:10,cat:"lobulos",q:"El pliegue de duramadre que separa el cerebro del cerebelo es la:",o:["Hoz del cerebro","Tienda del cerebelo","Diafragma selar","Hoz del cerebelo"],c:1,e:"La tienda (tentorio) del cerebelo separa los lóbulos occipitales del cerebelo."},
 {id:11,cat:"willis",q:"El polígono de Willis conecta el sistema:",o:["Carotídeo y el yugular","Carotídeo y el vertebro-basilar","Venoso y el meníngeo","Carotídeo externo e interno"],c:1,e:"El círculo de Willis interconecta el sistema carotídeo interno y el vertebro-basilar, dando circulación colateral."},
 {id:12,cat:"willis",q:"La arteria comunicante anterior une:",o:["Las dos cerebrales anteriores","Las dos cerebrales posteriores","La carótida interna y la basilar","Las dos arterias vertebrales"],c:0,e:"La comunicante anterior conecta las dos ACA por delante."},
 {id:13,cat:"willis",q:"Las arterias comunicantes posteriores conectan:",o:["Las dos cerebrales anteriores","La carótida interna y la cerebral posterior","Las dos arterias vertebrales","La basilar y la cerebral media"],c:1,e:"Las comunicantes posteriores unen el sistema carotídeo (carótida interna) con la cerebral posterior."},
 {id:14,cat:"willis",q:"Las arterias vertebrales se unen para formar la arteria:",o:["Basilar","Carótida interna","Cerebral media","Comunicante posterior"],c:0,e:"Ambas arterias vertebrales confluyen en la arteria basilar."},
 {id:15,cat:"willis",q:"La arteria carótida interna se origina de la:",o:["Aorta ascendente","Carótida común","Arteria subclavia","Arteria basilar"],c:1,e:"La carótida interna nace de la bifurcación de la carótida común."},
 {id:16,cat:"willis",q:"La arteria cerebral posterior (ACP) pertenece al sistema:",o:["Carotídeo","Vertebro-basilar","Venoso dural","Meníngeo"],c:1,e:"La ACP es rama terminal de la basilar (sistema vertebro-basilar)."},
 {id:17,cat:"willis",q:"La arteria cerebelosa posteroinferior (PICA) se origina de la:",o:["Arteria basilar","Arteria vertebral","Carótida interna","Cerebral media"],c:1,e:"La PICA nace de la arteria vertebral e irriga la parte inferior del cerebelo."},
 {id:18,cat:"willis",q:"La AICA y la SCA se originan de la:",o:["Arteria vertebral","Arteria basilar","Carótida interna","Comunicante posterior"],c:1,e:"La cerebelosa anteroinferior (AICA) y la superior (SCA) nacen de la basilar."},
 {id:19,cat:"territorios",q:"La arteria cerebral ANTERIOR (ACA) irriga la:",o:["Cara lateral del hemisferio","Cara medial del hemisferio","Cara inferior del cerebelo","Base del tronco encefálico"],c:1,e:"La ACA irriga la superficie medial; su infarto afecta la pierna y el pie contralaterales."},
 {id:20,cat:"territorios",q:"La arteria cerebral MEDIA (ACM) irriga la:",o:["Superficie medial del hemisferio","Superficie lateral del hemisferio","Superficie del lóbulo occipital","Superficie del tronco encefálico"],c:1,e:"La ACM irriga la cara lateral del hemisferio: motor/sensitivo de cara y brazo, y áreas del lenguaje en el hemisferio dominante."},
 {id:21,cat:"territorios",q:"La arteria cerebral POSTERIOR (ACP) irriga el:",o:["Lóbulo frontal","Lóbulo occipital","Lóbulo de la ínsula","Giro precentral"],c:1,e:"La ACP irriga el lóbulo occipital; su lesión produce déficit visual (hemianopsia)."},
 {id:22,cat:"territorios",q:"La debilidad predominante en la PIERNA contralateral sugiere infarto de la:",o:["ACM","ACA","ACP","PICA"],c:1,e:"El homúnculo de la pierna está en la cara medial (territorio de la ACA)."},
 {id:23,cat:"territorios",q:"La hemiparesia con afasia (cara/brazo y lenguaje) sugiere infarto de la:",o:["ACP derecha","ACM izquierda","ACA derecha","Cerebelosa superior"],c:1,e:"La ACM irriga áreas faciobraquiales y del lenguaje; su infarto en el hemisferio dominante da hemiparesia + afasia."},
 {id:24,cat:"territorios",q:"La hemianopsia (pérdida de campo visual) orienta a compromiso de la:",o:["ACA","ACM","ACP","Basilar"],c:2,e:"La corteza visual occipital depende de la ACP; su lesión causa déficit del campo visual."},
 {id:25,cat:"meninges",q:"El orden de las meninges de superficial a profunda es:",o:["Piamadre, aracnoides, duramadre","Duramadre, aracnoides, piamadre","Aracnoides, duramadre, piamadre","Duramadre, piamadre, aracnoides"],c:1,e:"De fuera a dentro: duramadre, aracnoides y piamadre."},
 {id:26,cat:"meninges",q:"El líquido cefalorraquídeo (LCR) circula en el espacio:",o:["Epidural","Subaracnoideo","Subdural","Extradural"],c:1,e:"El LCR ocupa el espacio subaracnoideo, entre aracnoides y piamadre."},
 {id:27,cat:"meninges",q:"Los senos venosos durales se localizan:",o:["En el espacio subaracnoideo","Entre las capas de la duramadre","Dentro del parénquima cerebral","Por debajo de la piamadre"],c:1,e:"Los senos durales corren entre las capas perióstica y meníngea de la duramadre."},
 {id:28,cat:"meninges",q:"El seno sagital superior recorre el borde de la:",o:["Tienda del cerebelo","Hoz del cerebro","Diafragma selar","Hoz del cerebelo"],c:1,e:"El seno sagital superior discurre por el borde superior de la hoz del cerebro."},
 {id:29,cat:"meninges",q:"La reunión de los senos venosos principales se denomina:",o:["Seno cavernoso","Confluencia de los senos","Golfo de la yugular","Seno esfenoparietal"],c:1,e:"El seno sagital superior y el recto confluyen en la confluencia de los senos (prensa de Herófilo)."},
 {id:30,cat:"meninges",q:"El drenaje venoso del encéfalo termina en las venas:",o:["Yugulares internas","Cavas superiores","Cerebrales medias","Maxilares"],c:0,e:"Los senos durales drenan en las venas yugulares internas."},
 {id:31,cat:"caso",q:"Un déficit neurológico focal de inicio SÚBITO por oclusión arterial corresponde a:",o:["ACV isquémico","Crisis migrañosa","Crisis epiléptica","Tumor de lento crecimiento"],c:0,e:"El ACV isquémico produce un déficit focal súbito por interrupción del flujo en un territorio arterial."},
 {id:32,cat:"caso",q:"Un paciente con hemiparesia derecha y afasia probablemente tiene compromiso de la:",o:["ACP derecha","ACM izquierda","ACA derecha","Cerebelosa izquierda"],c:1,e:"El lenguaje suele estar en el hemisferio izquierdo; la ACM izquierda explica hemiparesia derecha + afasia."},
 {id:33,cat:"caso",q:"La utilidad del círculo de Willis ante una oclusión es:",o:["Aumentar la presión arterial","Ofrecer circulación colateral","Reabsorber el LCR","Producir mielina"],c:1,e:"Las anastomosis del polígono de Willis permiten flujo colateral cuando se ocluye una arteria principal."},
 {id:34,cat:"caso",q:"Un ACV producido por rotura vascular con sangrado se denomina:",o:["Isquémico","Hemorrágico","Embólico","Lacunar"],c:1,e:"El ACV hemorrágico se debe a rotura de un vaso con sangrado intracraneal, a diferencia del isquémico."}
];'''
h=re.sub(r"const POOL=\[.*?\n\];", POOL, h, count=1, flags=re.S)
open(P,"w",encoding="utf-8").write(h)
print("cerebro POOL NBME · preguntas:", h.count('cat:"'))
